### PR TITLE
Delete code template

### PR DESCRIPTION
**Pull request by jerryy2021**
**Summary**

Completed delete code template feature; fixed code for utils functiion createOrUpdateTags

**Testing**

1. Login via login API
2. Delete code template API: Delete a code template by specifying an id (can be an existing id, an id that belongs to another user, or a non-existing id; the latter two cases would give appropriate error messages)

Issues to be closed by this PR: 
- https://github.com/Scriptorium-CSC309/web/issues/24

### CODE REVIEW

**Comment by Ram-Raghav-S** [comment]
@jerryy2021 some conflicts to resolve apparently. Ping me when they are resolved for a review

**Comment by jerryy2021** [comment]
@Ram-Raghav-S  Sorry about that. It's resolved now.

**Review by Ram-Raghav-S — CHANGES_REQUESTED** [review]
Typescript errors and compilation errors

image

image


Maybe as issue with how the conflicts were resolved?

**Comment by jerryy2021** [comment]
Oops, sorry about that. I should've pulled again after resolving conflicts here to double check. Now it should be good. Thanks!

**Comment by Ram-Raghav-S** [comment]
@jerryy2021 have some time to look at this?

**Review by Ram-Raghav-S — APPROVED** [review]

**Pull request merged**
